### PR TITLE
issue#235 Made it set lastModification in xml sitemap

### PR DESCRIPTION
**Pull request by WillBBP**
I just added the few lines below to the method computeUrlInformationFromSitemapDocument() in Doctrine/Phpcr/SitemapUrlInformationProvider.php so that where the sitemap document has a method getLastModification(), this method is used to set lastModification in the $urlInformation.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Can you have a look into #225 ? Maybe i still did that change there? Cause that PR does a bigger refactoring in the handling creating the values  - not in the usage.

**Comment by ElectricMaxxx** [comment]
Yea and now as i saw your code, i realized that it would implement a very special usecase. And that is the reason why i started to Do #225 cause you will be able to implement and register (tagged Service) to guess/vote the values of `UrlInformation`.

**Comment by WillBBP** [comment]
Hi, I'd like to have a go at making our stuff run with your #255 and see how it goes. Currently getting...

`InvalidConfigurationException: Invalid configuration for path "cmf_seo": Notice: Undefined index: content_listener in /vagrant/vendor/symfony-cmf/seo-bundle/DependencyInjection/Configuration.php line 48`

I'm guessing this isn't enough config anymore...

    cmf_seo:
        persistence:
            phpcr:
                enabled: true
                manager_name: ~
        sonata_admin_extension: true
        sitemap: true

Can you give me some info on the new configuration options?

**Comment by ElectricMaxxx** [comment]
That's a feature @dbu implemented or refectored. Maybe he has got a fast idea.

**Comment by dbu** [comment]
i will try to find some time tomorrow to work on the SeoBundle pull
request and hopefully get it ready to merge.

meanwhile, you might find a hint about the configuration looking at the
diff of #225 - or maybe we just have some bug in there. (well, we
certainly at least have a bug that we should report a clear error
instead of the fatal error you get)

**Comment by ElectricMaxxx** [comment]
@dbu but we shouldn't merge this one, right? (cause it is a detailed implementation) So i would suggest to implement a guesser with that implementation later.

**Comment by dbu** [comment]
yes lets wait until #225 is merged and then refactor this one (if its not already in #225)

**Comment by dbu** [comment]
okay, #225 has been merged. we only just started writing documentation, but the new approach would be to implement the GuesserInterface and tag it as guesser with a higher priority to set last modification before its set by something else. does that make sense? imho it makes more sense to build that in your project than inside this bundle. wdyt?

**Comment by WillBBP** [comment]
If only "business" hadn't just canned everything that was in our sprint and moved us onto something else with a crazy deadline :-(

**Comment by dbu** [comment]
oh noes! hope you can get back to this later.
ok if we close this issue then?

as a potential user of the bundle in a different context, your input in
#222 would be appreciated btw.

**Comment by WillBBP** [comment]
Yes, close it for now

**Pull request closed without merging**
