### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Peekmo**
Hello,

I added the french translation for different labels.

Regards,
Peekmo

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
@dbu task for you to check them? I don't understand them, or do we check those translations in generall?

**Comment by WouterJ** [comment]
99% of the translations are based on trust I think.

**Comment by ElectricMaxxx** [comment]
so then lets merge and thank @Peekmo  for his work.

**Comment by Peekmo** [comment]
No problem, I'm french and I needed this translations ;) They are probably not the best translations ever, but they are better than nothing :)

**Pull request merged**
