### PR TITLE
create xsd schema

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
...  for error handling, alternate locales and sitemap configuration.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #213 
| License       | MIT
| Doc PR        | none

do not merge until PR #196 is merged.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
should i add the one for #209 too?

**Comment by dbu** [comment]
if @benglass does not find time to add it in his PR, that would make sense, yes

**Comment by ElectricMaxxx** [comment]
OK, after my learnings last night, i think this woldn't be that hard, so you can merge his PR i think.

**Comment by dbu** [comment]
looks good to me 
@WouterJ may i ask you to double-check?

**Comment by ElectricMaxxx** [comment]
lets merge this when you are happy, will give @benglas a hand when he needs it and is ready.

**Pull request merged**
