### PR TITLE
check PHP 7

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
... just a try.

### CODE REVIEW

**Comment by WouterJ** [comment]
PHP 7 is already checked, by `nightly`. So this PR adds duplication and can be closed.

**Comment by ElectricMaxxx** [comment]
@WouterJ why not calling it directly `7.0` as it is available now?

**Comment by ElectricMaxxx** [comment]
btw: just wanted to have a try run, a i was sitting in a talk about it.

**Comment by WouterJ** [comment]
@ElectricMaxxx you're right, let's switch to PHP 7.0. When I find some time, I'll update all repositories with nightly -> 7.0 and fail_fast: true (another Travis speed optimalization I discovered yesterday).

**Comment by dbu** [comment]
:+1:

**Pull request closed without merging**
